### ISSUE TITLE
wish: move "references" to end up commit message, make it more compact

### ISSUE THREAD

**Issue by markstos** [sprintly/Sprintly-GitHub#24]
After using this tool and scanning our commit messages, they all now start with "References #..., " etc.  Especially on a mobile device where only the first bit may be visible, this is far less useful then seeing the commit message instead.  When two or three tickets are referenced, this becomes particularly unwieldy. I'd prefer an alternate syntax instead: 

    Here's my commit message. ( ref #X, ref #y )

This could possibly implemented with a format string in the configuration that allows people to choose how they want to the formatting to work.

**Comment by nicholasserra** [comment]
#35 was merged, which shortens the References syntax to Re. Hopefully that fixes this issue. Thanks!
