### ISSUE TITLE
OSError: [Errno 35] Resource temporarily unavailable

### ISSUE THREAD

**Issue by jakeatwork** [sprintly/Sprintly-GitHub#37]
I installed Sprintly-Github on my mac, installed the hook in my local project, can get the list of tasks/bugs/stories, but when I commit and select an item number to attach, I then get this error. This has happened to me before and I honestly can't remember what fixed it. I'm wondering if it's a permissions thing? I did install sprintly-github as sudo and i have brew python in addition to system python.

any ideas?

```
Traceback (most recent call last):
  File ".git/hooks/commit-msg.original", line 143, in <module>
    sys.exit(subprocess.call([original_commit_msg, sys.argv[1]]))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1231, in _execute_child
    self.pid = os.fork()
OSError: [Errno 35] Resource temporarily unavailable
```

**Comment by justinabrahms** [comment]
I suspect this has something to do with running out of file descriptors or
similar.

http://stackoverflow.com/a/22729602/4972

I think the solution is probably to increase the limit.
http://superuser.com/q/302754/45650 should have answers for you.

**Comment by jakeatwork** [comment]
@justinabrahms thanks for the quick reply. i just tried the solution and no go. still the same error. i'm running el capitan if that matters. any other ideas?

**Comment by nicholasserra** [comment]
Wondering if some of the subprocess handling in this package is not implemented totally correct. Going to take a look.

**Comment by jakeatwork** [comment]
ok...fixed the issue. i had the hook installed prior to a recent format of my computer. i reinstalled the hook and apparently that caused the issue. so what i did was run the `sprintly --uninstall-hook` command and then `cd .git/hooks/` and ran `rm commit-msg.original`. then reinstalled the hook via `sprintly --install-hook` and now everything works. thanks for the attention.
